export interface OfferMetadata {
  qualityGrade?: string;
  autoGeneratedAt?: Date;
  priceHistory?: Array<{
    oldPrice: number;
    newPrice: number;
    timestamp: Date;
    reason: string;
  }>;
  lastPriceUpdate?: {
    oldPrice: number;
    newPrice: number;
    timestamp: Date;
    reason: string;
  };
  acceptedAt?: Date;
  rejectionReason?: string;
  rejectedAt?: Date;
  cancellationReason?: string;
  cancelledAt?: Date;
  expiryReason?: string;
  expiryMetadata?: {
    expiredAt: Date;
    originalValidUntil: Date;
  };
}
