export enum MetricType {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY"
}

export enum MetricCategory {
  REVENUE = "REVENUE",
  TRANSACTIONS = "TRANSACTIONS",
  USERS = "USERS",
  PRODUCE = "PRODUCE",
  INSPECTIONS = "INSPECTIONS",
  OFFERS = "OFFERS"
} 