[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "gcc", "g++"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = [
    "npm install",
    "npm run build"
] 