[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/src/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
workdir = "/app"

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

# Database Configuration
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"

# Redis Configuration
REDIS_URL = "${{ Redis.URL }}"
CACHE_TTL = "300"
CACHE_MAX_ITEMS = "100"

# JWT Configuration
JWT_SECRET = "${{ JWT_SECRET }}"
JWT_EXPIRY = "15d"
JWT_REFRESH_EXPIRY = "60d"

# API Configuration
ALLOWED_ORIGINS = "https://${{ RAILWAY_PUBLIC_DOMAIN }}"
CORS_MAX_AGE = "3600"

[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "gcc", "g++"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "npm run prebuild",
    "npm run build",
    "cp -r scripts dist/"
]

[phases.db]
cmds = [
    "echo 'CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";' | psql ${{ Postgres.DATABASE_URL }}",
    "cat create_tables.sql | psql ${{ Postgres.DATABASE_URL }}"
]