[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "gcc", "g++"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"] 