[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run prebuild && npm run build && cp -r scripts dist/"

[deploy]
startCommand = "node dist/scripts/init-db.js && node dist/src/main.js"
workdir = "/app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

# Database Configuration
DATABASE_URL = "postgresql://${{ Postgres.USER }}:${{ Postgres.PASSWORD }}@${{ Postgres.HOST }}:${{ Postgres.PORT }}/${{ Postgres.DATABASE }}"

# Redis Configuration
REDIS_URL = "redis://:${{ Redis.PASSWORD }}@${{ Redis.HOST }}:${{ Redis.PORT }}"
CACHE_TTL = "300"
CACHE_MAX_ITEMS = "100"

# JWT Configuration (Make sure to set these in Railway's environment variables)
JWT_SECRET = "${{ JWT_SECRET }}"
JWT_EXPIRY = "15d"
JWT_REFRESH_EXPIRY = "60d"

# API Configuration
ALLOWED_ORIGINS = "https://${{ RAILWAY_PUBLIC_DOMAIN }}"
CORS_MAX_AGE = "3600"

[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "gcc", "g++"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run prebuild", "npm run build", "cp -r scripts dist/"] 