[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "docker run -p 3000:3000 ${RAILWAY_DOCKERFILE_IMAGE}"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "gcc", "g++"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "ls -la dist/"
]

[phases.install]
cmds = ["npm ci --only=production"]

[nixpacks]
start-command = "node dist/main.js" 