[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "gcc", "g++"]

[phases.build]
cmds = [
    "npm install",
    "npm run build"
]

[phases.install]
cmds = ["npm ci --only=production"]

[nixpacks]
start-command = "node dist/main.js" 