[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/src/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
workdir = "/app"

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

# Database Configuration
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"

# Redis Configuration
REDIS_URL = "${{ Redis.URL }}"
CACHE_TTL = "300"
CACHE_MAX_ITEMS = "100"

# JWT Configuration
JWT_SECRET = "${{ JWT_SECRET }}"
JWT_EXPIRY = "15d"
JWT_REFRESH_EXPIRY = "60d"

# API Configuration
ALLOWED_ORIGINS = "https://${{ RAILWAY_PUBLIC_DOMAIN }}"
CORS_MAX_AGE = "3600"

[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "gcc", "g++", "postgresql-client"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "npm run prebuild",
    "npm run build",
    "cp -r scripts dist/"
]

[phases.db]
cmds = [
    "echo 'Testing database connection...'",
    "psql ${{ Postgres.DATABASE_URL }} -c 'SELECT 1;'",
    
    "echo 'Dropping schema...'",
    "psql ${{ Postgres.DATABASE_URL }} -c 'DROP SCHEMA public CASCADE;'",
    "psql ${{ Postgres.DATABASE_URL }} -c 'CREATE SCHEMA public;'",

    "echo 'Creating extensions...'",
    "psql ${{ Postgres.DATABASE_URL }} -c 'CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";'",
    "psql ${{ Postgres.DATABASE_URL }} -c 'CREATE EXTENSION IF NOT EXISTS \"postgis\";'",
    "psql ${{ Postgres.DATABASE_URL }} -c 'CREATE EXTENSION IF NOT EXISTS \"pg_trgm\";'",

    "echo 'Creating trigger functions...'",
    "psql ${{ Postgres.DATABASE_URL }} -c 'CREATE OR REPLACE FUNCTION trigger_set_timestamp() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END; $$ language plpgsql;'",

    "echo 'Verifying UUID generation...'",
    "psql ${{ Postgres.DATABASE_URL }} -c 'SELECT uuid_generate_v4();'",

    "echo 'Running create_tables.sql...'",
    "cat create_tables.sql | psql ${{ Postgres.DATABASE_URL }}"
]