export enum ProduceStatus {
  DRAFT = 'DRAFT',
  LISTED = 'LISTED',
  PENDING_INSPECTION = 'PENDING_INSPECTION',
  INSPECTION_FAILED = 'INSPECTION_FAILED',
  SOLD = 'SOLD',
  ARCHIVED = 'ARCHIVED',
} 