export enum ProduceStatus {
  // Initial state
  AVAILABLE = "AVAILABLE",
  PENDING = "PENDING",

  // Assessment states
  PENDING_AI_ASSESSMENT = "PENDING_AI_ASSESSMENT",
  PENDING_INSPECTION = "PENDING_INSPECTION",
  ASSESSED = "ASSESSED",
  ASSESSMENT_FAILED = "ASSESSMENT_FAILED",

  // Progress states
  IN_PROGRESS = "IN_PROGRESS",
  FINAL_PRICE = "FINAL_PRICE",

  // Final states
  COMPLETED = "COMPLETED",
  SOLD = "SOLD",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}
