export enum ProduceStatus {
  AVAILABLE = 'AVAILABLE',
  PENDING_INSPECTION = 'PENDING_INSPECTION',
  REJECTED = 'REJECTED',
  IN_PROGRESS = 'IN_PROGRESS',
  SOLD = 'SOLD',
  CANCELLED = 'CANCELLED'
} 