export enum ProduceCategory {
  FOOD_GRAINS = 'FOOD_GRAINS',
  OILSEEDS = 'OILSEEDS',
  FRUITS = 'FRUITS',
  VEGETABLES = 'VEGETABLES',
  SPICES = 'SPICES',
  FIBERS = 'FIBERS',
  SUGARCANE = 'SUGARCANE',
  FLOWERS = 'FLOWERS',
  MEDICINAL_PLANTS = 'MEDICINAL_PLANTS'
} 