export enum OfferStatus {
  PENDING = 'PENDING',
  AUTO_GENERATED = 'AUTO_GENERATED',
  QUEUED = 'QUEUED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  WITHDRAWN = 'WITHDRAWN'
} 