import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddOfferMetadata1706724000000 implements MigrationInterface {
  name = 'AddOfferMetadata1706724000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Add metadata column
    await queryRunner.query(`
      ALTER TABLE "offers" 
      ADD COLUMN IF NOT EXISTS "metadata" jsonb;
    `);

    // Update existing auto-generated offers with basic metadata
    await queryRunner.query(`
      UPDATE "offers"
      SET "metadata" = jsonb_build_object(
        'autoGeneratedAt', created_at,
        'priceHistory', '[]'::jsonb
      )
      WHERE "isAutoGenerated" = true AND "metadata" IS NULL;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "offers" 
      DROP COLUMN IF EXISTS "metadata";
    `);
  }
} 