export enum NotificationType {
  NEW_OFFER = 'NEW_OFFER',
  AUTO_OFFER_CREATED = 'AUTO_OFFER_CREATED',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_REJECTED = 'OFFER_REJECTED',
  OFFER_EXPIRED = 'OFFER_EXPIRED',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
  QUALITY_ASSESSMENT_COMPLETED = 'QUALITY_ASSESSMENT_COMPLETED',
  SUPPORT_TICKET_UPDATED = 'SUPPORT_TICKET_UPDATED',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
} 