export enum NotificationType {
  // Quality related
  QUALITY_UPDATE = "QUALITY_UPDATE",
  QUALITY_ASSESSMENT_COMPLETED = "QUALITY_ASSESSMENT_COMPLETED",

  // Offer related
  NEW_OFFER = "NEW_OFFER",
  NEW_AUTO_OFFER = "NEW_AUTO_OFFER",
  OFFER_ACCEPTED = "OFFER_ACCEPTED",
  OFFER_REJECTED = "OFFER_REJECTED",
  OFFER_MODIFIED = "OFFER_MODIFIED",
  OFFER_PRICE_MODIFIED = "OFFER_PRICE_MODIFIED",
  OFFER_APPROVED = "OFFER_APPROVED",
  OFFER_EXPIRED = "OFFER_EXPIRED",
  OFFER_PRICE_UPDATE = "OFFER_PRICE_UPDATE",
  OFFER_STATUS_UPDATE = "OFFER_STATUS_UPDATE",

  // Inspection related
  INSPECTION_REQUEST = "INSPECTION_REQUEST",
  INSPECTION_REQUESTED = "INSPECTION_REQUESTED",
  INSPECTION_COMPLETED = "INSPECTION_COMPLETED",
  INSPECTION_CANCELLED = "INSPECTION_CANCELLED",
  INSPECTION_ASSIGNED = "INSPECTION_ASSIGNED",

  // Delivery related
  DELIVERY_WINDOW_STARTED = "DELIVERY_WINDOW_STARTED",
  DELIVERY_WINDOW_EXPIRED = "DELIVERY_WINDOW_EXPIRED",
  DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED",

  // Rating related
  RATING_REQUIRED = "RATING_REQUIRED",
  RATING_RECEIVED = "RATING_RECEIVED",

  // Transaction related
  TRANSACTION_UPDATE = "TRANSACTION_UPDATE",
  TRANSACTION_COMPLETED = "TRANSACTION_COMPLETED",
  TRANSACTION_CANCELLED = "TRANSACTION_CANCELLED",

  // Payment related
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",

  // Account related
  ACCOUNT_STATUS_UPDATE = "ACCOUNT_STATUS_UPDATE",
}
