export enum SystemConfigKey {
  MAX_DAILY_PRICE_UPDATES = "max_daily_price_updates",
  MAX_GEOSPATIAL_RADIUS_KM = "max_geospatial_radius_km",
  BASE_FEE_PERCENTAGE = "base_fee_percentage",
  MIN_INSPECTION_FEE = "min_inspection_fee",
  MAX_INSPECTION_FEE = "max_inspection_fee",
  INSPECTION_BASE_FEE = "inspection_base_fee",
  INSPECTION_FEE_PER_KM = "inspection_fee_per_km",
  USE_AUTO_INSPECTOR_ASSIGNMENT = "use_auto_inspector_assignment",
  AUTO_INSPECTOR_ASSIGNMENT_RADIUS_KM = "auto_inspector_assignment_radius_km",
  DEFAULT_BUYER_RADIUS_KM = "default_buyer_radius_km",
  MAX_BUYER_RADIUS_KM = "max_buyer_radius_km",
  DEFAULT_PRODUCE_SEARCH_RADIUS_KM = "default_produce_search_radius_km",
  MAX_PRODUCE_SEARCH_RADIUS_KM = "max_produce_search_radius_km",
  DEFAULT_INSPECTOR_RADIUS_KM = "default_inspector_radius_km",
  MAX_INSPECTOR_RADIUS_KM = "max_inspector_radius_km",
} 