export enum AdminActionType {
  BLOCK_USER = "BLOCK_USER",
  UNBLOCK_USER = "UNBLOCK_USER",
  DELETE_PRODUCE = "DELETE_PRODUCE",
  CANCEL_OFFER = "CANCEL_OFFER",
  CANCEL_TRANSACTION = "CANCEL_TRANSACTION",
  ASSIGN_INSPECTOR = "ASSIGN_INSPECTOR",
  UPDATE_SYSTEM_CONFIG = "UPDATE_SYSTEM_CONFIG",
} 